"""add position for employee

Revision ID: b5c838b07684
Revises: 693b5104b3ab
Create Date: 2023-03-17 19:07:09.280135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c838b07684'
down_revision = '693b5104b3ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('position', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'position')
    # ### end Alembic commands ###
